### ISSUE TITLE
Introduce impurities and secondary contents to ores

### ISSUE THREAD

**Issue by Josharias** [Terasology/ManualLabor#2]
I want extra substances to be contained in ores so that value is put on further processing substances before creating materials.
- Impurities are substances that do not have a use in the tool making process
- Secondary contents could be separated from the main item
  - would also help dilute the other impurities in the item by splitting the other substances between the two output items
  - can only extract one other substance at a time
  - crushed items can only separate out substances above a certain amount threshold
  - dust items can separate out a substance with any amount
  - items with a substance amount below a certain threshold would get a "small" variant of the item, making them unable to be used in normal recipes until combined together to create a larger mass of the item
- Add a block to do this work (Sifter?) that will consume water to produce separated materials.

**Comment by Cervator** [comment]
:exclamation: 

Want :D
